In [1]:
# Import the needed libraries
import numpy as np

**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [10]:
#First is to create the 10 x 10 array up random values.
num = np.random.random((10, 10)) #using the .random function
print("\t" "Original arrays")
print(num)

#Then to find the minimum and maximum values,

num_min, num_max = num.min(), num.max()
print("\t" "Minimum num and Maximum num:")
print(num_min, num_max)

	Original arrays
[[0.08586    0.19308757 0.19838829 0.11608412 0.52152083 0.38140299
  0.14976893 0.68386689 0.84182173 0.97311151]
 [0.69269488 0.46359069 0.50672512 0.02353054 0.30205388 0.31196039
  0.44272824 0.87425559 0.60099437 0.10460525]
 [0.41409932 0.99444105 0.27892739 0.06302874 0.82847215 0.91487965
  0.57618381 0.05481158 0.63879221 0.18511303]
 [0.28027854 0.40106507 0.53794422 0.11646339 0.247857   0.22739646
  0.46595789 0.3578214  0.4997648  0.89691513]
 [0.41510056 0.45714158 0.56089913 0.52094794 0.61291336 0.74267841
  0.64528698 0.68313862 0.69894406 0.42095325]
 [0.67181962 0.30009755 0.97575896 0.15777475 0.25408186 0.70702833
  0.23844258 0.00235486 0.18325071 0.65689083]
 [0.1100921  0.82053102 0.72792861 0.63791611 0.66538166 0.69153235
  0.40904496 0.7319516  0.457805   0.91448703]
 [0.3979721  0.12328922 0.96736078 0.91956649 0.91439147 0.51231544
  0.96346373 0.31863777 0.30992209 0.97681334]
 [0.93180413 0.08843661 0.91112492 0.56377924 0.38549606 0.5229

**15. Create a 2d array with 1 on the border and 0 inside**

In [19]:
x = np.ones((5, 5))
print("Orignal data")
print(x)

print("Data with 1 on the border and 0 inside")
x[1:-1, 1:-1]= 0
print(x)

Orignal data
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Data with 1 on the border and 0 inside
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
