In [1]:
# Import the needed libraries
import numpy as np

**72. How to swap two rows of an array?** 

In [5]:
my_array = np.arange(12).reshape(3,4)
print("Original arrange")
print(my_array)

print("Swapping my original array")

my_array_T = my_array.T
print(my_array_T)


Original arrange
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Swapping my original array
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


**75. How to compute averages using a sliding window over an array?**

import numpy as np
# need to create a function to return moving average
def moving_average(a, n) :
    test = np.cumsum(a, dtype=float)
    test[n:] = test[n:] - test[:-n]
    return test[n - 1:] / n
# this uses cumulative sum for calculation

Z = np.arange(20)

print(moving_average(Z,n=3))

In [8]:
import numpy as np
# need to create a function to return moving average
def moving_average(a, n) :
    test = np.cumsum(a, dtype=float)
    test[n:] = test[n:] - test[:-n]
    return test[n - 1:] / n
# this uses cumulative sum for calculation

Z = np.arange(20)

print(moving_average(Z,n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
